### ISSUE TITLE
is possible to content is a current div into page?

### ISSUE THREAD

**Issue by carlos-andres** [pushpendra10/tikslussticky#1]
Good Day, it´s an excelent plugin.

i like to know if in the content opton of sticky is possible to attach it into a current html div into page without clone it in the stick box?? 

``` javascript
$.fn.tikslussticky({
        content: $("#myCustomID").html(),
        /* this clone contents from my custom div. */
        /* for example i put a youtube iframe and i got two playing videos. . */
        customID:'stk_responsive1',
        stickAt:'top-left'
    });
```

**Comment by pushpendraas400** [comment]
Hi Carlos:
I have changed the code a little bit to suit your requirement.

Please, download updated tikslussticky.js file.

I have included two new callback functions that can be called before and after sticky creation.
see callbackPost and callbackPre function.
you can add html from function callback without cloning / duplicating code.
For this, what i have done is that i have removed orignal HTML code (in your case the iframe) after sticky creation using callbackPost function.

Here is the javascript: (please call inside $(document).ready)

``` javascript
                $(document).ready(function(){

                    $.fn.tikslussticky({

                    content:function()
                                {
                                return $('#videos').html(); //return content from the orignal div
                                },

                    customID:'youtube_videos',

                    stickAt:'bottom-center',

                    callbackPost:function()
                                {
                                $('#videos').remove(); //remove orignal div containing iframe
                                }

                    });
                    });

```

and the HTML I have used

``` html
<div id="videos">

<iframe width="560" height="315" src="https://www.youtube.com/embed/Rbku5hI8pG8" frameborder="0" allowfullscreen></iframe>

</div>
```

**Comment by pushpendraas400** [comment]
i am reopening this issue

**Comment by carlos-andres** [comment]
Good Day 

another way .. is for example use extra var: `currentID`  and add a switch or validation after this section   `$("head").append("<style>"+style+"</style>");`, (this is some dummy code) .. 

``` Javascript
if (currentID.length > 0) {
        $("#"+options.currentID).css({"display":"inline-block","position":"fixed","zIndex":9000000,"backgroundColor":options.bkColor,"color":options.fontColor,"fontSize":options.fontSize + "px","opacity":options.opacity,"padding":options.padding });
    } else {
        $("body").append("<div id='"+options.customID+"' style='position:fixed;' class='sticky'>"+options.content+"</div>");
}
```

Again Many Thanks..  it´s a great job!

p.d. in some cases for the center-left or right-left css it put contents inside a div on my template, and just add left:0px or right:0px and i´t works without margin 

``` CSS
        var styles={
            '.top-left':"top:0px;left:0px;",
            '.top-center':'top:0px;bottom:inherit !important;',
            '.top-right':'right:0px;top:0px;,left:inherit !important;bottom:inherit !important; text-align: right;',
            '.center-left':"left:0px !important;right:inherit !important;bottom:inherit !important;",
            '.center-right':"right:0px !important;left:inherit !important;bottom:inherit !important; text-align: right;",
            '.bottom-left':"left:0px !important;bottom:0px !important;top:inherit !important;",
            '.bottom-center':'bottom:0px!important;top:inherit !important;right:inherit !important;',
            '.bottom-right':'bottom:0px!important;right:0px!important;left:inherit !important;top:inherit; text-align: right;'
        };
```
